# Generated by Django 3.2.4 on 2021-07-06 04:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import institutuff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Er.', 'Er.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=10, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('id_code', models.CharField(max_length=15)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recent_passport_size_photo', models.FileField(blank=True, null=True, upload_to='documents_photos/')),
                ('position_in_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_enrollment', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^20[0-9][0-9]/[0-9]{2}/[0-9]{2}$'), django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('userName', models.OneToOneField(on_delete=models.SET(institutuff.models.sentinel.get_sentinel_user), related_name='institute', to=settings.AUTH_USER_MODEL, validators=[institutuff.models.validate_group])),
            ],
        ),
    ]
