# Generated by Django 2.2.3 on 2021-07-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
