# Generated by Django 2.2.3 on 2019-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20190725_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='be_program_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Full fee', 'Full fee')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='msc_program_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Full fee', 'Full fee')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phd_program_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Full fee', 'Full fee')], max_length=10, null=True),
        ),
    ]
