# Generated by Django 2.2.3 on 2019-08-18 09:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_student_is_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='msc_ioe_roll_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phd_ioe_roll_number',
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='program_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='msc_program',
            field=models.CharField(blank=True, choices=[('MSI', 'MSc in Information & Communications Engineering (MScICE/MSI)'), ('MSCS', 'MSc in Computer Systems and Knowledge engineering (MScCKSE/MSCS)')], default=None, max_length=20, null=True),
        ),
    ]
