# Generated by Django 2.2.3 on 2019-08-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20190818_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phd_program_type',
        ),
        migrations.AlterField(
            model_name='student',
            name='msc_program_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Full Fee', 'Full Fee'), ('Sponsorship', 'Sponsorship')], max_length=10, null=True),
        ),
    ]
