# Generated by Django 2.2.3 on 2019-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20190818_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='msc_ioe_roll_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phd_ioe_roll_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='msc_program',
            field=models.CharField(blank=True, choices=[('MSICE', 'MSc in Information & Communications Engineering (MScICE/MSI)'), ('MSCSK', 'MSc in Computer Systems and Knowledge engineering (MScCKSE/MSCS)')], default=None, max_length=20, null=True),
        ),
    ]
