# Generated by Django 2.2.3 on 2019-08-19 10:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20190818_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurtherAcademicStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Masters', 'Masters'), ('PhD', 'PhD'), ('Post Doc.', 'Post Doc.')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('program_name', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('details', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_addresses', to='records.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='msc_program',
            field=models.CharField(blank=True, choices=[('MSICE', 'MSc in Information & Communications Engineering (MScICE)'), ('MSCSK', 'MSc in Computer Systems and Knowledge engineering (MScCKSE)')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='AcademicStatus',
        ),
        migrations.AddField(
            model_name='furtheracademicstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_further_academic_statuses', to='records.Student'),
        ),
    ]
