# Generated by Django 2.2.4 on 2019-08-20 03:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20190819_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtheracademicstatus',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
