# Generated by Django 2.2.3 on 2019-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20190819_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
