# Generated by Django 2.2.3 on 2019-08-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_student_date_updated'),
        ('records', '0015_address_street_address'),
    ]

    operations = [
    ]
