# Generated by Django 2.2.3 on 2020-06-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_remove_student_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
