# Generated by Django 3.2.4 on 2021-07-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_student_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='msc_program_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Full Fee', 'Full Fee'), ('Sponsorship', 'Sponsorship')], max_length=12, null=True),
        ),
    ]
