# Generated by Django 3.2.4 on 2021-07-30 15:10

from django.conf import settings
from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0019_alter_student_msc_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_account',
            field=models.OneToOneField(null=True, on_delete=models.SET(records.models.get_sentinel_user), related_name='student_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
