# Generated by Django 3.2.4 on 2021-08-08 20:18

from django.conf import settings
from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0020_student_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(records.models.get_sentinel_user), related_name='student_user', to=settings.AUTH_USER_MODEL, validators=[records.models.validate_group]),
        ),
    ]
